<a href="https://colab.research.google.com/github/rimjhimittal/COE_SEM5/blob/main/ADS_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy (Numerical Python)
1. NumPy is the fundamental package for scientific computing in Python.
2. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices),
3. An assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, and many more.
4. At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance.

![1.png](attachment:1.png)

# NumPy Array vs. Python Sequneces
1. NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically)
2. NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

# Installing and Importing NumPy
1. NumPy can be installed with conda, with pip
2. If we use conda, we can install NumPy as : conda install numpy
3. If we use pip, we can install NumPy as : pip install numpy
4. Once the package has been installed, it need to be imported.

In [1]:
!pip install numpy
import numpy as np

# NumPy Array Basics
NumPy’s array class is called ndarray. It is also known by the alias array. The more important attributes of an ndarray object are:
1. ndarray.ndim- the number of axes (dimensions) of the array
2. ndarray.shape- the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension.
3. ndarray.size- the total number of elements of the array. This is equal to the product of the elements of shape.
4. ndarray.dtype- an object describing the type of the elements in the array. NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
5. ndarray.itemsize- the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8)
6. ndarray.data-the buffer containing the actual elements of the array.

# Creating Arrays
There are 6 general mechanisms for creating arrays:
1. Conversion from other Python structures (i.e. lists and tuples)
2. Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)
3. Replicating, joining, or mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Using Random Sampling
6. Use of special library functions (e.g., Pandas, scipy)

# 1. Creating Arrays- From Python Sequneces
NumPy arrays can be defined using Python sequences such as lists and tuples. Lists and tuples are defined using [...] and (...), respectively.
Lists and tuples can define ndarray creation:
1. a list of numbers will create a 1D array,
2. a list of lists will create a 2D array,
3. further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.

In [ ]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]],
                    [[5, 6], [7, 8]]])

In [ ]:
print(a2D)

[[1 2]
 [3 4]]


In [ ]:
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
print('Dimensions-',a3D.ndim)
print('Shape-',a3D.shape)
print('Size-',a3D.size)
print('Dtype-',a3D.dtype)
print('ItemSize-',a3D.itemsize)

Dimensions- 3
Shape- (2, 2, 2)
Size- 8
Dtype- int32
ItemSize- 4


# 2. Creating Arrays- Intrinsic Functions
NumPy has over 40 built-in functions for creating arrays as laid out in the Array creation routines.
These functions can be split into roughly three categories, based on the dimension of the array they create:
1. 1D arrays
2. 2D arrays
3. ndarrays

# 2.1-1D Array Creation Functions
The 1D array creation functions e.g. numpy.linspace and numpy.arange generally need at least two inputs, start and stop.


# numpy.arange
numpy.arange creates arrays with regularly incrementing values.
1. Syntax: numpy.arange([start, ]stop, [step, ], dtype=None, like=None)

In [ ]:
a=np.arange(10)
b=np.arange(2, 10, dtype=float)
c=np.arange(2, 3, 0.1)
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[2. 3. 4. 5. 6. 7. 8. 9.]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


# numpy.linspace
It will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values.
1. Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype= None, axis=0)

In [ ]:
np.linspace(1., 4., 6,retstep=True)

(array([1. , 1.6, 2.2, 2.8, 3.4, 4. ]), 0.6)

# 2.2-2D array creation functions
The 2D array creation functions e.g. numpy.eye, numpy.diag, and numpy.vander define properties of special matrices represented as 2D arrays.

# numy.eye
np.eye(n, m) defines a 2D identity matrix.
1. Syntax: numpy.eye(N, M=None, k=0, dtype=, order=‘C or F', *, like=None)
 k denotes Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.


In [ ]:
import numpy as np
a=np.eye(3,dtype=np.int)
b=np.eye(3, 5,k=2,dtype=np.float)
print(a)
print(b)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# numpy.diag
numpy.diag Extract a diagonal or construct a diagonal array.
1. Syntax: numpy.diag(v, k=0)
 If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.


In [ ]:
np.diag([1, 2, 3],k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)


array([1, 4])

# numpy.vander
numpy.vander  constructs a  Vandermonde matrix i.e. the columns of the output matrix are powers of the input vector.
Syntax: numpy.vander(x, N=None, increasing =False)
 Parameters: x: 1-D array, N= Number of columns  (default  square array with N=len(x);  Increasing- Order of the powers of the columns. If True, the powers increase from left to right, if False (the default) they are reversed.

In [ ]:
x=np.linspace(0, 2, 5)
print(x)
np.vander(x, 3)

[0.  0.5 1.  1.5 2. ]


array([[0.  , 0.  , 1.  ],
       [0.25, 0.5 , 1.  ],
       [1.  , 1.  , 1.  ],
       [2.25, 1.5 , 1.  ],
       [4.  , 2.  , 1.  ]])

In [ ]:
np.vander([1, 2, 3, 4], 3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [ ]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [ ]:
np.vander((1, 2, 3, 4), 4,increasing=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

# 2.3-General ndarray creation functions
The ndarray creation functions e.g. numpy.ones, numpy.zeros, numpy.identity and numpy.empty define arrays based upon the desired shape.


# numpy.ones
numpy.ones Return a new array of given shape and type, filled with ones.
1. Syntax:numpy.ones(shape, dtype=None, order='C', like=None)


In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2, 3, 2),dtype=np.float)

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

# numpy.zeros
numpy.zeros Return a new array of given shape and type, filled with zeros.
1. Syntax:numpy.zeros(shape, dtype=None, order='C', like=None)

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2, 3, 2),dtype=np.float)

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

# numpy.identity
numpy.identity Return the identity array
1. Syntax: numpy.identity(n, dtype=None, like=None)

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# numpy.empty
numpy.empty return a new array of given shape and type, without initializing entries.
1. Syntax: numpy.empty(shape, dtype=float, order='C', *, like=None)

In [ ]:
np.empty((1,5))

array([[0. , 0.5, 1. , 1.5, 2. ]])

# 3. Creating Arrays- Replicating, joining, or mutating existing arrays
New arrays can be created from existing arrays using routines like numpy.concatenate, numpy.block, numpy.vstack, numpy.hstack

# numpy.concatenate
Join a sequence of arrays along an existing axis.
1. Syntax: numpy.concatenate((a1, a2, …), axis=0, dtype=None, casting="same_kind")


In [ ]:
A = np.ones((2, 2))
print(A)
B=np.zeros((2,2))
print(B)
np.concatenate((A,B),axis=1)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

# numpy.block
Assemble an nd-array from nested lists of blocks.
1. Syntax:numpy.block(arrays)

In [ ]:
np.block([A,B])

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

# numpy.vstack
Stack arrays in sequence vertically
1. Syntax: numpy.vstack((arrays))


In [ ]:
np.vstack((A,B))


array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

# numpy.hstack
Stack arrays in sequence horizontally
1. Syntax: numpy.hstack((arrays))

In [ ]:
np.hstack((A,B))


array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

# 4. Creating Arrays from Disk
1. Delimited files such as comma separated value (csv) and tab separated value (tsv) files are used for programs like Excel and LabView.
2. NumPy has two standard routines for importing a file with delimited data numpy.loadtxt and numpy.genfromtxt

# numpy.loadtxt
1. numpy.loadtxt  Load data from a text file. Each row in the text file must have the same number of values.
1. Syntax: numpy.loadtxt(fname, dtype=, delimiter=None,skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, like=None)

In [ ]:
a=np.loadtxt('C:/Machine Learning/ML_Datasets/exam.txt',delimiter=',',dtype='str',skiprows=2,usecols=[0,2],max_rows=10)

In [ ]:
a

array([['-0.21371', '1'],
       ['-0.375', '1'],
       ['-0.51325', '1'],
       ['-0.52477', '1'],
       ['-0.39804', '1'],
       ['-0.30588', '1'],
       ['0.016705', '1'],
       ['0.13191', '1'],
       ['0.38537', '1'],
       ['0.52938', '1']], dtype='<U8')

# numpy.genfromtxt
1. When there are missing values in the file, then numpy.genfromtxt is used.
2. Syntax: numpy.genfromtxt (fname, dtype=, comments='#', delimiter=None, skip_header=0, skip_footer=0, missing_values=None, filling_values=None, usecols=None, names=None, usemask=False, loose=True, max_rows=None, encoding='bytes’)

In [ ]:
a=np.genfromtxt('C:/Machine Learning/ML_Datasets/exam.txt',delimiter=',',filling_values=99,names=['test1','test2','score'],skip_header=1)


In [ ]:
a

array([(-0.092742 ,  0.68494 ,  1.), (-0.21371  ,  0.69225 ,  1.),
       (-0.375    ,  0.50219 ,  1.), (-0.51325  ,  0.46564 ,  1.),
       (-0.52477  ,  0.2098  ,  1.), (-0.39804  ,  0.034357,  1.),
       (-0.30588  , -0.19225 ,  1.), ( 0.016705 , -0.40424 ,  1.),
       ( 0.13191  , -0.51389 ,  1.), ( 0.38537  , -0.56506 ,  1.),
       ( 0.52938  , -0.5212  ,  1.), ( 0.63882  , -0.24342 ,  1.),
       ( 0.73675  , -0.18494 ,  1.), ( 0.54666  ,  0.48757 ,  1.),
       ( 0.322    ,  0.5826  , 99.), ( 0.16647  ,  0.53874 ,  1.),
       (-0.046659 ,  0.81652 ,  1.), (-0.17339  ,  0.69956 ,  1.),
       (-0.47869  ,  0.63377 ,  1.), (-0.60541  ,  0.59722 ,  1.),
       (-0.62846  ,  0.33406 ,  1.), (-0.59389  ,  0.005117,  1.),
       (-0.42108  , -0.27266 ,  1.), (-0.11578  , -0.39693 ,  1.),
       ( 0.20104  , -0.60161 ,  1.), ( 0.46601  , -0.53582 ,  1.),
       ( 0.67339  , -0.53582 ,  1.), (-0.13882  ,  0.54605 ,  1.),
       (-0.29435  ,  0.77997 ,  1.), (-0.26555  ,  0.96272 ,  

# 5. Creating Arrays- Using Random Sampling
numpy.random.rand   Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1)
 1. Syntax: random.rand(d0, d1, ..., dn)
 where d0, d1, …, dnint, optional

In [ ]:
np.random.rand(2,3)

array([[0.61439077, 0.09107385, 0.46559313],
       [0.97424018, 0.26366128, 0.60711341]])

In [ ]:
np.random.randn(2,3)

array([[-0.12579905,  0.74063798, -0.78023859],
       [-0.05990145,  0.14777583, -0.03168951]])

# Misc Random Functions
Besides random.rand numpy provodes functions like random.randn, random.randint, random.randintegers, etc.

In [ ]:
np.random.randint(10,size=(2,3))

array([[1, 9, 4],
       [1, 5, 0]])